use_frameworks!

target 'LyonPodTestLibrary_Example' do
  pod 'LyonPodTestLibrary', :path => '../'
  
  
  #pod 'AFNetworking', '2.3.0'
end
 
post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['ENABLE_BITCODE'] = 'NO'
        end
    end
end

